image: docker-registry.sensorberg.io:443/android/docker-android-ci:0.2.4

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

stages:
  - test

#cache:
#  key: $CI_PROJECT_NAME
#  paths:
#    - .gradle/wrapper
#    - .gradle/caches

merge_request:
  stage: test
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "*/build/reports"
  tags:
    - docker
    - hetzner
    - kvm
    - x86
  only:
    - merge_requests
  script:
    # build
    - ./gradlew clean testDebugUnitTest lintDebug assembleDebug assembleAndroidTest

    # Boot emulator & Run Android Tests
    - ./ci_scripts/emulator/boot_emulator.sh
    - ./ci_scripts/emulator/waitForEmulator.sh
    - ./gradlew cAT

deploy_release:
  stage: test
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/reports"
      - "*/build/outputs/aar"
  tags:
    - docker
    - hetzner
    - kvm
    - x86
  only:
    - tags
  script:
    # build
    - ./gradlew clean testReleaseUnitTest assemble assembleAndroidTest
    - ./gradlew uploadArchives